//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostgreSQLDAL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostgreSQLDAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功 的本地化字符串。
        /// </summary>
        internal static string connect_success {
            get {
                return ResourceManager.GetString("connect_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bit
        ///bool
        ///box
        ///bytea
        ///char
        ///cidr
        ///circle
        ///date
        ///decimal
        ///float4
        ///float8
        ///inet
        ///int2
        ///int4
        ///int8
        ///interval
        ///json
        ///jsonb
        ///line
        ///lseg
        ///macaddr
        ///money
        ///path
        ///point
        ///polygon
        ///serial2
        ///serial4
        ///serial8
        ///text
        ///time
        ///timetz
        ///timestamp
        ///timestamptz
        ///tsquery
        ///tsvector
        ///txid_snapshot
        ///uuid
        ///varbit
        ///varchar
        ///xml
        ///(Domain)
        ///(Type) 的本地化字符串。
        /// </summary>
        internal static string dataTypes {
            get {
                return ResourceManager.GetString("dataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 
        ///column_name as FIELDNAME,
        ///data_type as FIELDTYPE,
        ///coalesce(character_maximum_length,numeric_precision,-1) as FIELDLENGTH,
        ///numeric_scale as FIELDSCALE,
        ///case is_nullable when &apos;YES&apos; then 0 else 1 end as FIELDISNULL,
        ///case when b.pk_name is null then 0 else 1 end as FIELDPRIMARYKEY,
        ///column_default as FIELDDEFAULT,
        ///c.DeText as FIELDCOMMENTS
        ///from information_schema.columns 
        ///left join (
        ///    select pg_attr.attname as colname,pg_constraint.conname as pk_name from pg_constraint  
        ///    inner join pg_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string designTableScript {
            get {
                return ResourceManager.GetString("designTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT tablename FROM pg_tables WHERE schemaname=&apos;public&apos; 的本地化字符串。
        /// </summary>
        internal static string loadTableScript {
            get {
                return ResourceManager.GetString("loadTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT viewname FROM pg_views WHERE schemaname = &apos;public&apos; 的本地化字符串。
        /// </summary>
        internal static string loadViewScript {
            get {
                return ResourceManager.GetString("loadViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM {0} LIMIT {1} OFFSET {2} 的本地化字符串。
        /// </summary>
        internal static string openTableScript {
            get {
                return ResourceManager.GetString("openTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM {0} LIMIT {1} OFFSET {2} 的本地化字符串。
        /// </summary>
        internal static string openViewScript {
            get {
                return ResourceManager.GetString("openViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap postgresql_close_16 {
            get {
                object obj = ResourceManager.GetObject("postgresql_close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap postgresql_log {
            get {
                object obj = ResourceManager.GetObject("postgresql_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap postgresql_open_16 {
            get {
                object obj = ResourceManager.GetObject("postgresql_open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string prompt {
            get {
                return ResourceManager.GetString("prompt", resourceCulture);
            }
        }
    }
}
