//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDAL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLDAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Data Source = {0}\AppData\SQL.db 的本地化字符串。
        /// </summary>
        internal static string AppSQL {
            get {
                return ResourceManager.GetString("AppSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DELETE FROM TB_CONNECTION WHERE NAME=@name 的本地化字符串。
        /// </summary>
        internal static string DeleteConnectScript {
            get {
                return ResourceManager.GetString("DeleteConnectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DELETE FROM TB_CONFIG WHERE NAME=@name 的本地化字符串。
        /// </summary>
        internal static string DeleteDriverScript {
            get {
                return ResourceManager.GetString("DeleteDriverScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO TB_CONNECTION VALUES(@connectName, @user, @file, @host, @port, @password, @connectionString, @driverName)&quot; 的本地化字符串。
        /// </summary>
        internal static string InsertConnectScript {
            get {
                return ResourceManager.GetString("InsertConnectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO TB_CONFIG(name, assemblyName, namespaceName, className) VALUES(@name, @assemblyName, @namespaceName, @className) 的本地化字符串。
        /// </summary>
        internal static string InsertDriverScript {
            get {
                return ResourceManager.GetString("InsertDriverScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO TB_SELECT VALUES(@selectName, @script, @connectName, @databaseName) 的本地化字符串。
        /// </summary>
        internal static string InsertSelectScript {
            get {
                return ResourceManager.GetString("InsertSelectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 
        ///tb_connection.name,
        ///tb_connection.user, 
        ///tb_connection.password,
        ///tb_connection.file,
        ///tb_connection.host,
        ///tb_connection.port,
        ///tb_connection.connectionString,
        ///tb_config.assemblyName,
        ///tb_config.namespaceName,
        ///tb_config.className
        ///FROM 
        ///tb_connection, 
        ///tb_config
        ///WHERE 
        ///tb_connection.driverName = tb_config.name 的本地化字符串。
        /// </summary>
        internal static string LoadConnectScript {
            get {
                return ResourceManager.GetString("LoadConnectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM tb_config 的本地化字符串。
        /// </summary>
        internal static string LoadDriverScript {
            get {
                return ResourceManager.GetString("LoadDriverScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM TB_SELECT WHERE DATABASE=@database AND CONNECT=@connect 的本地化字符串。
        /// </summary>
        internal static string LoadSelectScript {
            get {
                return ResourceManager.GetString("LoadSelectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPDATE TB_CONNECTION SET 
        ///user = @user,  
        ///password = @password,  
        ///file = @file,  
        ///host = @host,  
        ///port = @port, 
        ///connectionString = @connectionString,  
        ///driverName = @driverName
        ///WHERE name = @name 的本地化字符串。
        /// </summary>
        internal static string UpdateConnectScript {
            get {
                return ResourceManager.GetString("UpdateConnectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPDATE TB_SELECT SET CONTENTS=@script WHERE NAME=@selectName AND CONNECT=@connectName AND DATABASE=@databaseName 的本地化字符串。
        /// </summary>
        internal static string UpdateSelectScript {
            get {
                return ResourceManager.GetString("UpdateSelectScript", resourceCulture);
            }
        }
    }
}
