//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDAL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OracleDAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功 的本地化字符串。
        /// </summary>
        internal static string connect_success {
            get {
                return ResourceManager.GetString("connect_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHAR
        ///NCHAR
        ///VARCHAR2
        ///VARCHAR
        ///NVARCHAR2
        ///CLOB
        ///NCLOB
        ///LONG
        ///NUMBER
        ///BINARY_FLOAT
        ///BINARY_DOUBLE
        ///DATE
        ///INTERVAL DAY TO SECOND
        ///INTERVAL YEAR TO MONTH
        ///TIMESTAMP
        ///TIMESTAMP WITH TIME ZONE
        ///TIMESTAMP WITH LOCAL TIME ZONE
        ///BLOB
        ///BFILE
        ///RAW
        ///LONG RAW
        ///ROWID
        ///CHARACTER
        ///CHARACTER VARYING
        ///CHAR VARYING
        ///NATIONAL CHARACTER
        ///NATIONAL CHAR
        ///NATIONAL CHAR
        ///NATIONAL CHAR
        ///NATIONAL CHARACTER VARYING
        ///NATIONAL CHAR VARYING
        ///NCHAR VARYING
        ///NUMERIC
        ///DECIMAL
        ///INTEGER
        ///INT
        ///SMALLINT
        ///FLOAT
        ///DOUBLE PRECISION
        ///REAL
        ///(COMPLE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string dataTypes {
            get {
                return ResourceManager.GetString("dataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///          A .column_name AS FIELDNAME,
        ///          A .data_type AS FIELDTYPE,
        ///          NVL (DECODE (A .data_type,	&apos;NUMBER&apos;, A .data_precision,A .data_length),&apos;&apos;) AS FIELDLENGTH,
        ///          NVL (A .data_scale, 0) AS FIELDSCALE,
        ///          DECODE(A .nullable, &apos;N&apos;, 1, 0) AS FIELDISNULL,
        ///          DECODE (E .key1, &apos;P&apos;, 1, 0) AS FIELDPRIMARYKEY,
        ///          A .data_default AS FIELDDEFAULT,
        ///          f.comments AS FIELDCOMMENTS
        ///        FROM
        ///          user_tab_columns A,
        ///          user_col_comments f, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string designTableScript {
            get {
                return ResourceManager.GetString("designTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from user_tables 的本地化字符串。
        /// </summary>
        internal static string loadTableScript {
            get {
                return ResourceManager.GetString("loadTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from user_views 的本地化字符串。
        /// </summary>
        internal static string loadViewScript {
            get {
                return ResourceManager.GetString("loadViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT* FROM (SELECT &quot;SQL_TABLE&quot;.*, ROWNUM &quot;SQL_ROWNUM&quot; FROM(SELECT &quot;{0}&quot;.*, ROWID &quot;SQL_ROWID&quot; FROM &quot;{1}&quot;) &quot;SQL_TABLE&quot; WHERE ROWNUM &lt;= {2}) WHERE SQL_ROWNUM &gt; {3} 的本地化字符串。
        /// </summary>
        internal static string openTableScript {
            get {
                return ResourceManager.GetString("openTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT* FROM (SELECT &quot;SQL_TABLE&quot;.*, ROWNUM &quot;SQL_ROWNUM&quot; FROM(SELECT &quot;{0}&quot;.*, ROWID &quot;SQL_ROWID&quot; FROM &quot;{1}&quot;) &quot;SQL_TABLE&quot; WHERE ROWNUM &lt;= {2}) WHERE SQL_ROWNUM &gt; {3} 的本地化字符串。
        /// </summary>
        internal static string openViewScript {
            get {
                return ResourceManager.GetString("openViewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap oracle_close_16 {
            get {
                object obj = ResourceManager.GetObject("oracle_close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap oracle_logo {
            get {
                object obj = ResourceManager.GetObject("oracle_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap oracle_open_16 {
            get {
                object obj = ResourceManager.GetObject("oracle_open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string prompt {
            get {
                return ResourceManager.GetString("prompt", resourceCulture);
            }
        }
    }
}
